INPUT_PIN = "inputPin"
POWER_PIN = "powerPin"
LED_PIN = "ledPin"
DE_CONSTRUCTOR = "deConstructor"
CONSTRUCTOR = "constructor"
FROM = "from"
TO = "to"
TIMESTAMP = "timestamp"
ACTION = "action"
SET_MODE_AWAY = "setModeAway"
SET_MODE_HOME = "setModeHome"


DEVICE_OBJECT = "deviceObject"
DEVICE_CONFIG = "deviceConfig"
DEVICE= "device"
DEVICES= "devices"

SOURCE = "source"
TARGET = "target"
TYPE = "type"
CONTROL = "control"
EVENT = "event"
OP_CODE = "opcode"
PARAMS = "params"
DATA = "data"

CONDITION = "condition"
STATE = "state"
NEXT_STATE = "nextState"
ACTIONS = "actions"
NORMAL = "normal"
ELEVATED = "elevated"
BEGIN = "begin"
AWAY = "away"
HOME = "home"
MODE = "mode"
MESSAGE = "message"
SEND= "send"
COMMAND = "command"
DEBUG_LOG = "debugLog"

